export const MLB_TEAMS: Record<number, { name: string; abbreviation: string; league: string; division: string }> = {
  108: { name: 'Los Angeles Angels', abbreviation: 'LAA', league: 'AL', division: 'West' },
  109: { name: 'Arizona Diamondbacks', abbreviation: 'ARI', league: 'NL', division: 'West' },
  110: { name: 'Baltimore Orioles', abbreviation: 'BAL', league: 'AL', division: 'East' },
  111: { name: 'Boston Red Sox', abbreviation: 'BOS', league: 'AL', division: 'East' },
  112: { name: 'Chicago Cubs', abbreviation: 'CHC', league: 'NL', division: 'Central' },
  113: { name: 'Cincinnati Reds', abbreviation: 'CIN', league: 'NL', division: 'Central' },
  114: { name: 'Cleveland Guardians', abbreviation: 'CLE', league: 'AL', division: 'Central' },
  115: { name: 'Colorado Rockies', abbreviation: 'COL', league: 'NL', division: 'West' },
  116: { name: 'Detroit Tigers', abbreviation: 'DET', league: 'AL', division: 'Central' },
  117: { name: 'Houston Astros', abbreviation: 'HOU', league: 'AL', division: 'West' },
  118: { name: 'Kansas City Royals', abbreviation: 'KC', league: 'AL', division: 'Central' },
  119: { name: 'Los Angeles Dodgers', abbreviation: 'LAD', league: 'NL', division: 'West' },
  120: { name: 'Washington Nationals', abbreviation: 'WSH', league: 'NL', division: 'East' },
  121: { name: 'New York Mets', abbreviation: 'NYM', league: 'NL', division: 'East' },
  133: { name: 'Oakland Athletics', abbreviation: 'OAK', league: 'AL', division: 'West' },
  134: { name: 'Pittsburgh Pirates', abbreviation: 'PIT', league: 'NL', division: 'Central' },
  135: { name: 'San Diego Padres', abbreviation: 'SD', league: 'NL', division: 'West' },
  136: { name: 'Seattle Mariners', abbreviation: 'SEA', league: 'AL', division: 'West' },
  137: { name: 'San Francisco Giants', abbreviation: 'SF', league: 'NL', division: 'West' },
  138: { name: 'St. Louis Cardinals', abbreviation: 'STL', league: 'NL', division: 'Central' },
  139: { name: 'Tampa Bay Rays', abbreviation: 'TB', league: 'AL', division: 'East' },
  140: { name: 'Texas Rangers', abbreviation: 'TEX', league: 'AL', division: 'West' },
  141: { name: 'Toronto Blue Jays', abbreviation: 'TOR', league: 'AL', division: 'East' },
  142: { name: 'Minnesota Twins', abbreviation: 'MIN', league: 'AL', division: 'Central' },
  143: { name: 'Philadelphia Phillies', abbreviation: 'PHI', league: 'NL', division: 'East' },
  144: { name: 'Atlanta Braves', abbreviation: 'ATL', league: 'NL', division: 'East' },
  145: { name: 'Chicago White Sox', abbreviation: 'CWS', league: 'AL', division: 'Central' },
  146: { name: 'Miami Marlins', abbreviation: 'MIA', league: 'NL', division: 'East' },
  147: { name: 'New York Yankees', abbreviation: 'NYY', league: 'AL', division: 'East' },
  158: { name: 'Milwaukee Brewers', abbreviation: 'MIL', league: 'NL', division: 'Central' },
}

export const TEAM_ABBREVIATION_TO_ID: Record<string, number> = {}
for (const [id, team] of Object.entries(MLB_TEAMS)) {
  TEAM_ABBREVIATION_TO_ID[team.abbreviation] = Number(id)
}

export const MLB_API_BASE = 'https://statsapi.mlb.com/api/v1'
export const MLB_API_V1_1 = 'https://statsapi.mlb.com/api/v1.1'

export const NEWS_SOURCES = [
  { id: 'mlb.com', name: 'MLB.com', url: 'https://www.mlb.com/feeds/news/rss.xml', enabled: true },
  { id: 'espn', name: 'ESPN', url: 'https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/news', enabled: true },
  { id: 'foxsports', name: 'FOX Sports', url: 'https://api.foxsports.com/sports-data/v2/sports/baseball/mlb/news', enabled: false },
]

export const ALERT_IMPORTANCE_COLORS: Record<string, string> = {
  high: 'text-red-400 border-red-500/30 bg-red-500/10',
  medium: 'text-amber-400 border-amber-500/30 bg-amber-500/10',
  low: 'text-blue-400 border-blue-500/30 bg-blue-500/10',
}

export const TEAM_LOGOS: Record<string, string> = {
  ARI: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/109.svg',
  ATL: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/144.svg',
  BAL: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/110.svg',
  BOS: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/111.svg',
  CHC: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/112.svg',
  CIN: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/113.svg',
  CLE: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/114.svg',
  COL: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/115.svg',
  CWS: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/145.svg',
  DET: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/116.svg',
  HOU: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/117.svg',
  KC: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/118.svg',
  LAA: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/108.svg',
  LAD: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/119.svg',
  MIA: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/146.svg',
  MIL: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/158.svg',
  MIN: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/142.svg',
  NYM: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/121.svg',
  NYY: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/147.svg',
  OAK: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/133.svg',
  PHI: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/143.svg',
  PIT: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/134.svg',
  SD: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/135.svg',
  SEA: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/136.svg',
  SF: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/137.svg',
  STL: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/138.svg',
  TB: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/139.svg',
  TEX: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/140.svg',
  TOR: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/141.svg',
  WSH: 'https://www.mlbstatic.com/team-logos/team-cap-on-dark/120.svg',
}

export const TEAM_COLORS: Record<string, string> = {
  ARI: '#A71930',
  ATL: '#CE1141',
  BAL: '#DF4601',
  BOS: '#BD3039',
  CHC: '#0E3386',
  CIN: '#C6011F',
  CLE: '#00385D',
  COL: '#33006F',
  CWS: '#27251F',
  DET: '#0C2340',
  HOU: '#002D62',
  KC: '#004687',
  LAA: '#003263',
  LAD: '#005A9C',
  MIA: '#00A3E0',
  MIL: '#FFC52F',
  MIN: '#002B5C',
  NYM: '#002D72',
  NYY: '#003087',
  OAK: '#003831',
  PHI: '#E81828',
  PIT: '#FDB827',
  SD: '#2F241D',
  SEA: '#0C2C56',
  SF: '#FD5A1E',
  STL: '#C41E3A',
  TB: '#092C5C',
  TEX: '#003278',
  TOR: '#134A8E',
  WSH: '#AB0003',
}

export const VENUE_COORDS: Record<string, { lat: number; lon: number; name: string }> = {
  ARI: { lat: 33.4457, lon: -112.0668, name: 'Chase Field' },
  ATL: { lat: 33.8908, lon: -84.4680, name: 'Truist Park' },
  BAL: { lat: 39.2840, lon: -76.6217, name: 'Oriole Park at Camden Yards' },
  BOS: { lat: 42.3467, lon: -71.0972, name: 'Fenway Park' },
  CHC: { lat: 41.9484, lon: -87.6553, name: 'Wrigley Field' },
  CWS: { lat: 41.8301, lon: -87.6338, name: 'Guaranteed Rate Field' },
  CIN: { lat: 39.0975, lon: -84.5067, name: 'Great American Ball Park' },
  CLE: { lat: 41.4961, lon: -81.6852, name: 'Progressive Field' },
  COL: { lat: 39.7559, lon: -104.9942, name: 'Coors Field' },
  DET: { lat: 42.3390, lon: -83.0485, name: 'Comerica Park' },
  HOU: { lat: 29.7572, lon: -95.3556, name: 'Minute Maid Park' },
  KC: { lat: 39.0517, lon: -94.4804, name: 'Kauffman Stadium' },
  LAA: { lat: 33.8003, lon: -117.8827, name: 'Angel Stadium' },
  LAD: { lat: 34.0739, lon: -118.2398, name: 'Dodger Stadium' },
  MIA: { lat: 25.7781, lon: -80.2196, name: 'LoanDepot Park' },
  MIL: { lat: 43.0267, lon: -87.9712, name: 'American Family Field' },
  MIN: { lat: 44.9818, lon: -93.2782, name: 'Target Field' },
  NYM: { lat: 40.7568, lon: -73.8462, name: 'Citi Field' },
  NYY: { lat: 40.8296, lon: -73.9262, name: 'Yankee Stadium' },
  OAK: { lat: 38.5851, lon: -121.5033, name: 'Sutter Health Park' },
  PHI: { lat: 39.9061, lon: -75.1665, name: 'Citizens Bank Park' },
  PIT: { lat: 40.4468, lon: -79.9899, name: 'PNC Park' },
  SD: { lat: 32.7076, lon: -117.1571, name: 'Petco Park' },
  SEA: { lat: 47.5914, lon: -122.3328, name: 'T-Mobile Park' },
  SF: { lat: 37.7786, lon: -122.3893, name: 'Oracle Park' },
  STL: { lat: 38.6226, lon: -90.1928, name: 'Busch Stadium' },
  TB: { lat: 27.7683, lon: -82.6534, name: 'Tropicana Field' },
  TEX: { lat: 32.7512, lon: -97.0830, name: 'Globe Life Field' },
  TOR: { lat: 43.6414, lon: -79.3894, name: 'Rogers Centre' },
  WSH: { lat: 38.8728, lon: -77.0074, name: 'Nationals Park' },
}

export function playerHeadshotUrl(playerId: number, size = 120): string {
  return `https://img.mlbstatic.com/mlb-photos/image/upload/w_${size},q_auto:best/v1/people/${playerId}/headshot/silo/current`
}
